package main

import (
	"fmt"
	"os"
)

func main() {
	// Create the oauth_resources.go file
	f, err := os.Create("../oauth_resources.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	// Write the package and imports
	fmt.Fprintln(f, "package main")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "// This file was generated by scripts/update_oauth_resources.go")
	fmt.Fprintln(f, "// Rerun scripts/update_oauth_resources.go to update this file")
	fmt.Fprintln(f, "// Please do not edit manually")
	fmt.Fprintln(f, "//")
	fmt.Fprintln(f, "// NOTE: The version lists are currently empty due to issues with the")
	fmt.Fprintln(f, "// upstream websites. This will be fixed in a future update.")
	fmt.Fprintln(f, "")

	// Write the iOS app versions
	fmt.Fprintln(f, "var iosAppVersionList = []string{}")
	fmt.Fprintln(f, "")

	// Write the Android app versions
	fmt.Fprintln(f, "var androidAppVersionList = []string{}")
	fmt.Fprintln(f, "")

	// Write the iOS OS versions
	fmt.Fprintln(f, "var iosOSVersionList = []string{}")
}