package main

// This file was generated by scripts/update_oauth_resources.go
// Rerun scripts/update_oauth_resources.go to update this file
// Please do not edit manually
//
// NOTE: The version lists are currently empty due to issues with the
// upstream websites. This will be fixed in a future update.

var iosAppVersionList = []string{}

var androidAppVersionList = []string{}

var iosOSVersionList = []string{}
