name: Build and Push Redlib to GHCR

on:
  workflow_run:
    workflows: ["Release Build"]
    types:
      - completed
  workflow_dispatch:

env:
  REGISTRY_IMAGE: ghcr.io/cat-ling/redlib

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { platform: linux/amd64, target: x86_64-unknown-linux-musl }
          - { platform: linux/arm64, target: aarch64-unknown-linux-musl }
          - { platform: linux/arm/v7, target: armv7-unknown-linux-musleabihf }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-arch
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: ${{ matrix.platform }}
          build-args: TARGET=${{ matrix.target }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          echo "$digest" > "/tmp/digests/digest-${{ matrix.target }}.txt"

      - name: Upload digest artifact
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.target }}
          path: /tmp/digests/digest-${{ matrix.target }}.txt
          if-no-files-found: error
          retention-days: 1

      - name: Inspect pushed image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}
